# https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      # Starting with version 3.0.0, these libraries uses a different package namespace.
      - dependency-name: "com.sun.xml.bind:jaxb-core"
      - dependency-name: "com.sun.xml.bind:jaxb-impl"
